### ISSUE TITLE
NVIDIA Problematic SVN certificate with repo

### ISSUE THREAD

**Issue by gdicker1** [EarthWorksOrg/EarthWorks#10]
Original issue: https://github.com/ESCOMP/EarthWorks/issues/2

Description by @cponder 
> This setup command
> 
> ./manage_externals/checkout_externals -v
> gives these failure messages
> 
>     svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags/chem_proc5_0_04 /lustre/fsw/devtech/hpc-devtech/cponder/EarthWorks/2023-03-08/CESM/components/cam/chem_proc
> ERROR:root:Command '['svn', 'checkout', '--quiet', 'https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags/chem_proc5_0_04', '/lustre/fsw/devtech/hpc-devtech/cponder/EarthWorks/2023-03-08/CESM/components/cam/chem_proc']' returned non-zero exit status 1.
> ERROR:root:Failed with output:
>     svn: E170013: Unable to connect to a repository at URL 'https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags/chem_proc5_0_04'
>     svn: E230001: Server SSL certificate verification failed: issuer is not trusted
> 
> ERROR: In directory
>     /lustre/fsw/devtech/hpc-devtech/cponder/EarthWorks/2023-03-08/CESM
> Process did not run successfully; returned status 1:
>     svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/tools/proc_atm/chem_proc/release_tags/chem_proc5_0_04 /lustre/fsw/devtech/hpc-devtech/cponder/EarthWorks/2023-03-08/CESM/components/cam/chem_proc
> See above for output from failed command.

**Comment by gdicker1** [comment]
Carl, I just learned of this issue like 15 minutes ago. Best of luck fixing it.

**Comment by cponder** [comment]
Try updating the config-file in the repo.
The clone-edit-clone doesn't work because of the inconsistency that it creates.

**Comment by gdicker1** [comment]
There's coming work to update the EarthWorkOrg/CAM to a newer tag from ESCOMP/CAM. For now you can try creating a branch based off EarthWorksOrg/CAM and then merging in a newer ESCOMP/CAM tag (or head of develop) to address this for yourself. If it goes well, I would more than welcome a PR in EarthWorksOrg/CAM that updates it.

**Comment by cponder** [comment]
Can you give me the commands to do this? I've manages to mess this up in the past.

**Comment by supreethms1809** [comment]
@cponder Thanks for reporting this. 
Long term fix: Update Externals_CAM.cfg to use the git protocal and point chem proc to git repo. This has been done in the latest version of CESM beta tags and this will eventually gets merged into Earthworks as we update our CAM tags. 

Short term fix: 

- I can create branch for CAM with a change pointing chem_proc to git. you can just use new branch in your External.cfg
- Secondly, We don't get the certificate in other machines like Cheyenne, Gust, Perlmutter. You could run the manage_externals/checkout on Cheyenne and 'scp' them over to Selene. 

Please let me know which is convenient for you.

**Comment by cponder** [comment]
Supreeth -- yeah -- could you please create the branch? Also that way i can test the updated code to see if it has any issues before the merge happens.

**Comment by supreethms1809** [comment]
@cponder I created a new branch for you to test. And here are some instructions to get it.
```
git clone git@github.com:EarthWorksOrg/EarthWorks.git
cd Earthworks
git checkout update_component_chem_proc
./manage_externals/checkout_externals -v
```
Please let me know how this turns out.

**Comment by cponder** [comment]
No errors in the checkout, thanks!
Dunno if we should close this now, or wait until things get merged into the trunk.

**Comment by supreethms1809** [comment]
@cponder thanks for testing it. Lets keep this open till we merge. We need to check if you can build and run the compsets without errors as expected. 
I’ll submit a PR for this change.

**Comment by gdicker1** [comment]
I think this issue has been resolved or at least gone stale, so I'm closing it for now.
