### ISSUE TITLE
inconsistency between cam and cmeps

### ISSUE THREAD

**Issue by dazlich** [EarthWorksOrg/EarthWorks#11]
The fully-coupled model will not compile anymore when I check out the v1 main branch of EarthWorks.
Specifically, it appears that cam is no longer consistent with cmeps. Formerly, cmeps/cesm/nuopc_cap_shared/seq_dry_dep.F90 declared dheff as a rank 1 array. Now dheff is declared a rank 2 array in shr_dry_dep.f90. Our cam/src/chemistry/mozart/mo_neu_wetdep.F90 uses dheff as a rank-1 array. ESCOMP/CAM cam_development branch uses dheff as a rank-2 array.

Our develop branch of cmeps has the older version with the rank-1 array. It's the main branch that has got ahead of CAM.

**Comment by gdicker1** [comment]
@dazlich does this issue still apply after merging PR #14?

**Comment by dazlich** [comment]
No, that takes care of it.

Don

On Jun 28, 2023, at 7:32 PM, gdicker1 ***@***.***> wrote:


** Caution: EXTERNAL Sender **


@dazlich<https://github.com/dazlich> does this issue still apply after merging PR #14<https://github.com/EarthWorksOrg/EarthWorks/pull/14>?
