### ISSUE TITLE
Incorporate git-fleximod tool

### ISSUE THREAD

**Issue by gdicker1** [EarthWorksOrg/EarthWorks#47]
As the cesm2_3_beta18 tag nears creation, ESCOMP/CESM is transitioning away from the [manage_externals](https://github.com/ESMCI/manage_externals) tool to the [git-fleximod](https://github.com/ESMCI/git-fleximod) tool. This switches from a (entirely) custom management tool that leverages basic git functions to a python tool that extends the git submodule utilities.

Whenever we decide to incorporate newer CESM tags (than cesm2_3_alpha17a, where we currently are) we will need to look out for this and make changes to either continue using the `manage_externals/checkout_externals` work flow or to adopt `git fleximod` and git submodules.

**Comment by gdicker1** [comment]
Closed by merge of #69

**Comment by dazlich** [comment]
These associated PRs need to be updated
EarthWorksOrg /mpas-ocean PR #15
EarthWorksOrg /mpas-seaice PR #17
EarthWorksOrg /mpas-framework PR #10
EarthWorksOrg /CMEPS PR #12
EarthWorksOrg/EarthWorks PR #75

**Comment by dazlich** [comment]
Also, I have merge issues to deal with with EarthWorksOrg /mpas-ocean PR #15
