### ISSUE TITLE
Bug in cime_config/config_compsets.xml

### ISSUE THREAD

**Issue by dazlich** [EarthWorksOrg/EarthWorks#49]
Line 104 closes the comment which is not supposed to closed until the next line.

**Comment by gdicker1** [comment]
Thanks for the catch, this should be fixed now by force-push:
 https://github.com/EarthWorksOrg/EarthWorks/blob/7bd2f8fcbb2224a150f0e08f96e56dce78d951e0/cime_config/config_compsets.xml#L103-L106
