### ISSUE TITLE
MPAS-O doesn't build with GCC/13.2 on Derecho

### ISSUE THREAD

**Issue by gdicker1** [EarthWorksOrg/EarthWorks#79]
When trying to upgrade the software stack in #77, I discovered that the mpas_ocn_okubo_weiss.F doesn't seem to be buildable with the Derecho software stack using the gcc/13.2 module. As I post this, it is a low priority item.

I started the normal ew-pr test category using `create_test` and saw that only the CHAOS2000dev tests that use GCC (test name contains "`_gnu`") failed to build. Examining the `bld/*.bldlog*` files for the cases showed the following output.

From CHAOS2000dev gcc/13.2 `bld/ocn.bldlog*`file for a CHAOS2000dev build (reposted from [EarthWorksOrg/ccs_config_cesm PR#29](https://github.com/EarthWorksOrg/ccs_config_cesm/pull/29))

```
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:74:21:

   74 |          type(c_ptr), value       :: array
      |                     1
Error: Type name 'c_ptr' at (1) is ambiguous
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:77:24:

   77 |          type(c_funptr), value    :: compare ! int (*compare)(const void*, const void*)
      |                        1
Error: Type name 'c_funptr' at (1) is ambiguous
f951: Warning: Nonexistent include directory '/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/gnu/mpich/nodebug/threads/finclude' [-Wmissing-include-dirs]
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:1159:87:

 1159 |       call qsort(c_loc(stats(1)), elemCount, elemSize, c_funloc(compareRealDescending))
      |                                                                                       1
Error: Type mismatch in argument 'array' at (1); passed TYPE(c_ptr) to REAL(4)
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:1159:87:

 1159 |       call qsort(c_loc(stats(1)), elemCount, elemSize, c_funloc(compareRealDescending))
      |                                                                                       1
Error: Type mismatch in argument 'compare' at (1); passed TYPE(c_funptr) to REAL(4)
```

**Comment by gdicker1** [comment]
Sounds good! Just stressing again this isn't pressing - I don't think we _need_ to fix this in the next couple of weeks.

**Comment by dazlich** [comment]
@gdicker1  - I just went to test it my self with the latest develop branch - builds and runs. Apparently this one sorted itself out. I'll close it if there are no objections.

**Comment by dazlich** [comment]
This is a branch I cloned last week.

On Dec 10, 2024, at 10:09 AM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


Just to clarify, did you just clone the develop branch, or did you modify a case to use a gcc/13.2 compiled stack?

**Comment by gdicker1** [comment]
> @gdicker1 - I just went to test it my self with the latest develop branch - builds and runs. Apparently this one sorted itself out. I'll close it if there are no objections.

Sorry bad question from me, not much clearer. Could you confirm what version of gcc the test referenced here used?

**Comment by dazlich** [comment]
software_environment.txt:GNU_VERSION=12.2.0

**Comment by gdicker1** [comment]
Thanks that clears it up!

I guess it makes sense to close this since we don't encounter it on the develop or main branches. We can refer to this issue or re-open it whenever we upgrade the gcc software stack.

**Comment by dazlich** [comment]
Closed, as the main and develop branches are not using version 13.2. May be revisited in the future.
