### ISSUE TITLE
BUILD FAIL: cam.buildlib - Unable to open MODULE file phys_control.mod

### ISSUE THREAD

**Issue by neil9876** [EarthWorksOrg/EarthWorks#85]
I am attempting to set up EarthWorks under Linux (on narval.alliancecan.ca) with the following dependencies:
nvhpc 23.9
ESMF 8.7.0
PIO 2.6.2
openmpi 4.1.5
HDF5 1.13.2
NETCDF-C 4.9.2
NETCDF-FORTRAN 4.6.1
(not using PNETCDF)
SZIP 2.1.1
gcc 12.3
cmake 3.31.0

I have also attached my config files in case they help. I am attempting to build a case with --res mpasa120_mpasa120 --compset F2000climo and it fails with the following error:

ERROR: BUILD FAIL: cam.buildlib failed, cat /project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/bld/atm.bldlog.241205-003138

The error from atm.bldlog.241205-003138 is below:

NVFORTRAN-F-0004-Unable to open MODULE file phys_control.mod (/lustre06/project/6024112/ntandon/my_earthworks_sandbox/components/cam/src/dynamics/mpas/driver/cam_mpas_subdriver.F90: 15)
NVFORTRAN/x86-64 Linux 23.9-0: compilation aborted
gmake[2]: *** [Makefile:274: cam_mpas_subdriver.o] Error 2
gmake[1]: *** [Makefile:114: all] Error 2
gmake: *** [/project/6024112/ntandon/EarthWorks_F2000_120j/Tools/Makefile:583: libmpas] Error 2

ERROR: Command gmake complib -j 1 COMP_NAME=cam COMPLIB=/project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/bld/lib/libatm.a -f /project/6024112/ntandon/EarthWorks_F2000_120j/Tools/Makefile CIME_MODEL=cesm  SMP=FALSE CASEROOT="/project/6024112/ntandon/EarthWorks_F2000_120j" CASETOOLS="/project/6024112/ntandon/EarthWorks_F2000_120j/Tools" CIMEROOT="/lustre06/project/6024112/ntandon/my_earthworks_sandbox/cime" SRCROOT="/lustre06/project/6024112/ntandon/my_earthworks_sandbox" COMP_INTERFACE="nuopc" COMPILER="nvhpc" DEBUG="FALSE" EXEROOT="/project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/bld" RUNDIR="/project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/run" INCROOT="/project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/bld/lib/include" LIBROOT="/project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/bld/lib" MACH="narval" MPILIB="openmpi" NINST_VALUE="c1a1l1i1o1r1" OS="LINUX" PIO_VERSION=2 SHAREDLIBROOT="/project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/bld" BUILD_THREADED="FALSE" USE_ESMF_LIB="TRUE" USE_MOAB="FALSE" CAM_CONFIG_OPTS="-phys cam6" COMP_ATM="cam" COMP_ICE="cice" COMP_GLC="sglc" COMP_LND="clm" COMP_OCN="docn" COMP_ROF="mosart" COMP_WAV="swav" USE_TRILINOS="FALSE" USE_ALBANY="FALSE" USE_PETSC="FALSE"   USER_CPPDEFS='    -DPLON=1 -DPLAT=1 -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_ROF=1 -DNUM_COMP_INST_WAV=1 -DNUM_COMP_INST_IAC=1 -DNUM_COMP_INST_ESP=1 -DPLEV=32 -DPCNST=34 -DPCOLS=16 -DPSUBCOLS=1 -DN_RAD_CNST=30 -DPTRM=1 -DPTRN=1 -DPTRK=1 -DSPMD -DMODAL_AERO -DMODAL_AERO_4MODE  -DCLUBB_SGS -DCLUBB_CAM -DNO_LAPACK_ISNAN -DCLUBB_REAL_TYPE=dp -DMODEL_ -DMODEL_CESM -DHEMCO_CESM -DUSE_REAL8' failed with rc=2

I would appreciate any guidance.

[config_files.zip](https://github.com/user-attachments/files/18025486/config_files.zip)

**Comment by dazlich** [comment]
@gdicker1 - does this problem look familiar to you?

**Comment by neil9876** [comment]
@gdicker1 - Full atm.bldlog is attached. I think a possible relevant error earlier in the file is shown below.
```
gmake[1]: Leaving directory '/project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120j/bld/atm/obj/mpas'
rm buffer.F90

 err:

cat: Srcfiles: No such file or directory

```
Does this indicate that mpas didn't build properly?

Based on [this page](https://groups.google.com/g/mpas-atmosphere-help/c/sH38ZCi0oOU), I thought MPAS could be built without PNetCDF. (I have been running CESM2 without PNetCDF because the alliancecan HPC systems don't have PNetCDF modules available.) But it seems like such a setup hasn't been tested much with MPAS, so I could see that being an issue. I will try to build PNetCDF myself and see how that goes.

If any other issues pop out of the atm.bldlog, please let me know.

[atm.bldlog.241205-003138.txt](https://github.com/user-attachments/files/18029474/atm.bldlog.241205-003138.txt)

**Comment by dazlich** [comment]
@neil9876 - perusing one of my cases, it appears that the mpas code has its own Makefile, and Srcfiles is for building the rest of the cam code. I presume your bld/atm/obj directory has a mpas subdirectory with lots of mpas*.o file? So I'm guessing the mpas part build, but somehow mkSrcfiles failed to generate your Srcfiles.

**Comment by gdicker1** [comment]
Unfortunately that `cat: Srcfiles` line shows up even in successful builds (annoying red herring).

Thanks for sharing the file, that helps me see that there is no line like `mpifort ... phys_control.F90` - so phys_control.F90 isn't building before cam_mpas_subdriver.F90 like we'd expect. I agree with dazlich that something could be wrong with the generation of the Depends file (which is generated from Srcfiles). Is there any content in the `bld/atm/obj/Srcfiles` associated with this case? What about `bld/atm/obj/Depends`?

Have you tried a `./case.build --clean-all` command before trying another build? Cleaning and rebuilding should regenerate the Srcfiles and Depends. 

If cleaning doesn't work, you may be able to get things to succeed by editing the `${CASEDIR}/Tools/Makefile` and adding 'phys_control.o' to the dependencies for libmpas near line 568, like this:

```
libmpas: cam_abortutils.o physconst.o phys_control.o
```

**Comment by neil9876** [comment]
@gdicker1 Thanks very much! I rebuilt with pnetcdf 1.14.0 (and accordingly rebuilt pio and esmf), and the same error occurred. So pnetcdf doesn't appear to be the issue here. I then tried the Makefile edit that you suggested, and atm then built successfully. In my case, I had to change line 582 from

`libmpas: cam_abortutils.o physconst.o`

to 

`libmpas: cam_abortutils.o physconst.o phys_control.o`

Since the Makefile in `${CASEDIR}/Tools/Makefile` is symbolically linked to `cime/CIME/Tools/Makefile`, you could consider updating the Makefile in the source package, if this might be an issue that affects others.

I am now dealing with a cesm build error that I will post about separately.

**Comment by gdicker1** [comment]
@neil9876 glad that helped! I'll close this for now.

Thanks for pointing this out! I will make changes to CIME to address this in the near future.
