### ISSUE TITLE
gptl build failed

### ISSUE THREAD

**Issue by neil9876** [EarthWorksOrg/EarthWorks#86]
I am attempting to set up EarthWorks under Linux (on narval.alliancecan.ca) with the following dependencies:
nvhpc 23.9
cuda 12.2
ESMF 8.7.0
PIO 2.6.2
openmpi 4.1.5
HDF5 1.13.2
NetCDF-C 4.9.2
NetCDF-FORTRAN 4.6.1
PNetCDF 1.14.0
SZIP 2.1.1
gcc 12.3
cmake 3.31.0

I have also attached my config files in case they help. I am attempting to build a case with --res mpasa120_mpasa120 --compset F2000climo and it fails with the following error:

`Building gptl with output to file /project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120u/bld/gptl.bldlog.241206-131922
   Calling /project/6024112/ntandon/my_earthworks_sandbox/cime/CIME/build_scripts/buildlib.gptl
ERROR: /project/6024112/ntandon/my_earthworks_sandbox/cime/CIME/build_scripts/buildlib.gptl FAILED, cat /project/6024112/ntandon/earthworks2_3/EarthWorks_F2000_120u/bld/gptl.bldlog.241206-131922

I have attached the gptl.bldlog. The error appears to relate to invalid options used in one of the gptl compilation commands. Could it be that these options were for older compilers and need to be updated?

[config_files.zip](https://github.com/user-attachments/files/18042131/config_files.zip)
[gptl.bldlog.241206-124657.txt](https://github.com/user-attachments/files/18042133/gptl.bldlog.241206-124657.txt)

**Comment by neil9876** [comment]
@gdicker1 - The nvhpc compilers were in my path. However, it appears that loading the cuda module after loading the nvhpc module creates problems. So I switched the order to load cuda before loading nvhpc, and that resolved the issue. I'm new to cuda, as I didn't need it for cesm, so perhaps those more familiar with cuda would know the reason for this order sensitivity.

**Comment by gdicker1** [comment]
I'm not 100% sure on the reason why, I think it's really specific to the site/machine you are running on and the details of how the modules are implemented on the system. I think we had a similar issue on NCAR systems, but I've just defaulted to loading cuda first and then the compilers on any system I try now.

If you still need help with gptl could you indicate what help you need? If not, it would help if you'd close this thread (so I don't think it's active).
